### ISSUE TITLE
Cannot start this projekt from Node.js

### ISSUE THREAD

**Issue by dkarl403** [microsoftgraph/angular-snippets-rest-sample#3]
[npm-debug.zip](https://github.com/microsoftgraph/angular-snippets-rest-sample/files/568365/npm-debug.zip)
Look at log.

**Comment by DianeD** [comment]
Hi @dkarl403 . I'm unable to repro this issue on a couple PCs. What platform are you using? I read that some common causes of this might be outdated npm cache, port number in use, firewalls, or http-server host localhost vs. 12.0.0.1.

**Comment by DianeD** [comment]
Hi @dkarl403 . Thanks for reporting this issue. Please reopen it if you're still having problems.
